#!/bin/bash

function __START__ {
  if [[ $1 == "sundarenius" ]];
    then
        echo $1;
        sshUrlSplit=(${2//:/ })
        urlPrefixed=${sshUrlSplit[0]}-$1:${sshUrlSplit[1]}
        git clone $urlPrefixed
        # cd in to directory
        split=(${2//// })
        z=${split[1]}
        folderName=(${z//.git/ })
        echo $folderName
        path=$(cd "$(dirname "$folderName")"; pwd -P)/$(basename "$folderName")
        cd $path
        git config user.name "Håkan Sundström"
        git config user.username "sundarenius"
        git config user.email "sundarenius@gmail.com"
        if [[ $3 == "n" ]];
          then
            echo -e '\nHit [Ctrl]+[D] to exit this child shell.'
            $SHELL
        fi
    elif [[ $1 = 'hakkespro' ]];
      then
        echo $1;
        sshUrlSplit=(${2//:/ })
        urlPrefixed=${sshUrlSplit[0]}-$1:${sshUrlSplit[1]}
        git clone $urlPrefixed
        # cd in to directory
        split=(${2//// })
        z=${split[1]}
        folderName=(${z//.git/ })
        echo $folderName
        path=$(cd "$(dirname "$folderName")"; pwd -P)/$(basename "$folderName")
        cd $path
        git config user.name "Håkan Sundström"
        git config user.username "hakkespro"
        git config user.email "hakan.sundstrom@bambora.com"
        if [[ $3 == "n" ]];
          then
            echo -e '\nHit [Ctrl]+[D] to exit this child shell.'
            $SHELL
        fi
    else
      echo Provide me a correct username
      echo cat this path to watch the code and usernames:
      echo Do a: \"which "${0##*/}"\" and cat that path
      echo Example:
      echo "${0##*/}" [username] [github-ssh-url]
    fi
}

__START__ $1 $2 $3;
