#!/bin/bash

function __NAVIGATE__ {
  # cd in to directory
  split=(${1//// })
  z=${split[1]}
  folderName=(${z//.git/ })
  echo $folderName
  path=$(cd "$(dirname "$folderName")"; pwd -P)/$(basename "$folderName")
  cd $path
  if [[ $2 ]];
    then
      echo -e '\nHit [Ctrl]+[D] to exit this child shell.'
      $SHELL
  fi
}

function __CLONE__ {
  if [[ $1 == "sundarenius" ]];
    then
        echo $1;
        sshUrlSplit=(${2//:/ })
        urlPrefixed=${sshUrlSplit[0]}-$1:${sshUrlSplit[1]}
        git clone $urlPrefixed
        __NAVIGATE__ $2 $3
    elif [[ $1 = 'hakkespro' ]];
      then
        echo $1;
        sshUrlSplit=(${2//:/ })
        urlPrefixed=${sshUrlSplit[0]}-$1:${sshUrlSplit[1]}
        git clone $urlPrefixed
        __NAVIGATE__ $2 $3
    elif [[ $1 = 'fork' ]];
      then
        echo Forking a repo
        echo CMD: gh repo fork $2
        gh repo fork $2
    else
      echo Provide me a correct username
      echo cat this path to watch the code and usernames:
      echo Do a: \"which "${0##*/}"\" and cat that path
      echo Example:
      echo "${0##*/}" [username] [github-ssh-url]
    fi
}

function __SET__ {
  if [[ $1 == "sundarenius" ]];
    then
      git config user.name "Håkan Sundström"
      git config user.username $1
      git config user.email "sundarenius@gmail.com"
    elif [[ $1 == "hakkespro" ]];
      then
        git config user.name "Håkan Sundström"
        git config user.username $1
        git config user.email "hakan.sundstrom@bambora.com"
    elif [[ $1 == "postnord" ]];
      then
        git config user.name "Håkan Sundström"
        git config user.username "hakansundstrom"
        git config user.email "hakan.sundstrom@postnord.com"
    elif [[ $1 == "knowit" ]];
      then
        git config user.name "Håkan Sundström"
        git config user.username "hakansundstrom"
        git config user.email "hakan.sundstrom@knowit.se"
    fi
}

if [[ $1 == "set" ]];
  then
    __SET__ $2;
  else
    __CLONE__ $1 $2 $3;
  fi
